// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6r2WdURsfTldnHsc39NrNG-QbCuaZRP0',
    appId: '1:615825126662:web:33f876c5fedda709e85a87',
    messagingSenderId: '615825126662',
    projectId: 'gospelvisiontv-5f3eb',
    authDomain: 'gospelvisiontv-5f3eb.firebaseapp.com',
    storageBucket: 'gospelvisiontv-5f3eb.firebasestorage.app',
    measurementId: 'G-5NLF3QM6ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07CKE70yDNOKHcjxM9NSuLQDyxRAdW_I',
    appId: '1:615825126662:android:046ab275e0ebe136e85a87',
    messagingSenderId: '615825126662',
    projectId: 'gospelvisiontv-5f3eb',
    storageBucket: 'gospelvisiontv-5f3eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlb9Lt0YZlrQyN06wuJRzGq-olWOW65U',
    appId: '1:615825126662:ios:a5173889983a4135e85a87',
    messagingSenderId: '615825126662',
    projectId: 'gospelvisiontv-5f3eb',
    storageBucket: 'gospelvisiontv-5f3eb.firebasestorage.app',
    iosBundleId: 'com.gospelvision.gvTv',
    iosClientId:
        '615825126662-cr9f9fbelcf9ps6q8n4i7pq83gihn57g.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHlb9Lt0YZlrQyN06wuJRzGq-olWOW65U',
    appId: '1:615825126662:ios:a5173889983a4135e85a87',
    messagingSenderId: '615825126662',
    projectId: 'gospelvisiontv-5f3eb',
    storageBucket: 'gospelvisiontv-5f3eb.firebasestorage.app',
    iosBundleId: 'com.gospelvision.gvTv',
    iosClientId:
        '615825126662-cr9f9fbelcf9ps6q8n4i7pq83gihn57g.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6r2WdURsfTldnHsc39NrNG-QbCuaZRP0',
    appId: '1:615825126662:web:8d64fbca4db00fa3e85a87',
    messagingSenderId: '615825126662',
    projectId: 'gospelvisiontv-5f3eb',
    authDomain: 'gospelvisiontv-5f3eb.firebaseapp.com',
    storageBucket: 'gospelvisiontv-5f3eb.firebasestorage.app',
    measurementId: 'G-QTM5F1YBRQ',
  );
}
